title: Spellzed DFIR Writeups
description: Writing about DFIR
show_downloads: false

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
